# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target 'Arrietty' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Arrietty
pod 'SnapKit', '~> 3.0.2'
pod 'Alamofire', '~> 4.0'
#pod 'Kingfisher', '~> 3.2.2' #装不上去好郁闷
end
